### ISSUE TITLE
Path dependent on relationships

### ISSUE THREAD

**Issue by garytaylor** [JsonApiClient/json_api_client#104]
In my application, I have a "line_item" which belongs to a "container".. The container is polymorphic.

When saving this line_item (we have chosen to save from the line_item rather than the container), I need the path to contain the container's type and id.  However, only the attributes are passed to the path class method.

Changing this involves doing a new requestor to maybe pass the relationships as a second parameter or even the resource itself, however I cant help thinking there should be an easier way ?

Do you have any suggestions or should I progress down this route ?

Cheers

Gary

**Comment by chingor13** [comment]
I don't have support for polymorphic paths right now. I need to think about how to implement it. If you have any suggestions, I'd love to hear them.

**Comment by jondruse** [comment]
This impacts belongs_to relationships also.  My issue is in trying to delete a record.

```
development> listing = DataServices::Listing.where(mls_id: "crmls_crib").find('listing_1').first
#<DataServices::Listing:@attributes={"id"=>"listing_1", "type"=>"listings", "mlsnum"=>"mlsnum_1", "city"=>"Huntington Beach", "state"=>"CA", "price_list"=>1000000, "beds"=>5, "baths"=>4, "updated_at"=>"2015-09-24T23:24:26", "mls_key"=>nil}>

development> listing.destroy
ArgumentError: Not all prefix parameters specified
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/json_api_client-1.0.0/lib/json_api_client/resource.rb:105:in `rescue in path'
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/json_api_client-1.0.0/lib/json_api_client/resource.rb:95:in `path'
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/json_api_client-1.0.0/lib/json_api_client/query/requestor.rb:52:in `resource_path'
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/json_api_client-1.0.0/lib/json_api_client/query/requestor.rb:30:in `destroy'
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/json_api_client-1.0.0/lib/json_api_client/resource.rb:376:in `destroy'
        from (irb):14
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
        from /Users/jondruse/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

```

I have found the following work around though

```
development> listing[:path] = {mls_id: 'crmls_crib'}
```

The simplest solution seems to be accepting a Hash on the save and destroy methods that gets saved into the path attribute.  I can submit a PR pretty easily for that if you think it's a viable solution.  Thanks!

**Comment by gaorlov** [comment]
This is at least partially addressed with the [`shallow_path`](https://github.com/JsonApiClient/json_api_client/pull/315) change. Please reopen if not
