### ISSUE TITLE
Only changed relationships converted to json

### ISSUE THREAD

**Issue by garytaylor** [JsonApiClient/json_api_client#105]
I have noticed that in the "Relations" class, the "attributes_for_serialization" only includes attributes that have changed.  
I am struggling with this as I have created a new resource with a new child resource and the relationships are not marked as changed.  If I force them to be changed during debugging - all works fine.

Is this the intended behaviour ?

Cheers

Gary

**Comment by chingor13** [comment]
This does not seem like it's intended. If it's a new resource, the relations should probably be marked as dirty still

**Comment by masimons** [comment]
I am also having issues with this. @garytaylor were you able to come up with a workaround?

**Comment by gaorlov** [comment]
This should be resolved. Please reopen if not
