### ISSUE TITLE
ability to have many sessions

### ISSUE THREAD

**Issue by babrovka** [JsonApiClient/json_api_client#116]
Is it possible to implement multi session behavior and have specific headers for each instance of client?
Something like this:
1. Create a new instance of api_client and pass headers to it
2. Communicate with API models through this instance using headers from '1'

Thanks in advance for your reply

**Comment by Fivell** [comment]
@babrovka , look at ```with_headers``` method

**Comment by gaorlov** [comment]
This looks resolved. Please reopen if not
