### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by bcm** [JsonApiClient/json_api_client#122]
It would be great to have some level of caching support in this library. Have you had any thoughts along those lines?

**Comment by sebastian-julius** [comment]
You can simply create your own `Connection` and use a custom Faraday middleware stack. You're super flexible with Faraday so have a look. E.e. https://github.com/plataformatec/faraday-http-cache

**Comment by bcm** [comment]
that is a fantastic suggestion. thanks!

**Comment by adisos** [comment]
@bcm @sebastian-julius 

Guys, do you have some examples?

**Comment by adisos** [comment]
I managed to fix this.

Some of `json_api_client`'s middlewares cuts off `If-None-Match header`, so I inserted `faraday-http-cache` header right before `Faraday::Adapter::HTTPClient` and it works perfectly.

**Comment by wafendy** [comment]
@adisos could you please share some example on how to set up caching using 'faraday-http-cache'?

**Comment by adisos** [comment]
@wafendy 
Sure, my `Base` class:
```ruby
module Api
  class Base < JsonApiClient::Resource
    # set the api base url in an abstract base class
    self.site = ENV.fetch('API_BASE_URL', 'http://localhost:3000/')

    connection do |conn|
      caching_options = {
        store: Rails.cache,
        shared_cache: false
      }
      caching_options[:logger] = Rails.logger if Rails.env.development?
      conn.faraday.builder.insert_before(
        Faraday::Adapter::HTTPClient,
        Faraday::HttpCache,
        caching_options
      )
    end
  end
end
```

**Comment by gaorlov** [comment]
This looks resolved. Please reopen if not
