### ISSUE TITLE
Support shallow routing for belongs_to?

### ISSUE THREAD

**Issue by jsamos** [JsonApiClient/json_api_client#180]
Unless I am mistaken, it seems belongs_to resources only support nested routes for find, update and delete. Has there been any thought about supporting shallow routes? Currently in have to create two classes: one with the belongs_to defined and the other without.

**Comment by chingor13** [comment]
The belongs_to is there for nested routes. If your API returns link definitions like the jsonapi.org spec provides, the client can follow those links without having to declare them in code.

Personally, I don't like to nest routes because you are required to know the parent's id in order to access the child resource(s). Instead, it could be a flat, root resource with a filter by the parent id (which is totally optional).

Is the issue that you have both a flat and nested resource together?

**Comment by jsamos** [comment]
Yes all of our apis have the `shallow: true` option set for nested routes.

so for instance we have something like

INDEX, CREATE
/orders/:id/invoices

and 

SHOW, UPDATE, DESTROY
/invoices/:id

Currently to support that I need

```
class Invoice < JsonApiClient
end

class Order::Invoice <  JsonApiClient
    belongs_to: order
end
```

**Comment by gottfrois** [comment]
Same issue here. Nested routes helps to reason about a resource in its context (an `invoice` comes from an `order`). But when you want to fetch invoice details, you simple hit the flat `/invoices/{id}` endpoint.

**Comment by remear** [comment]
My APIs use the same structure as described in other comments. I'd really like to see this implemented. Is there anything I/we could do to get this going?

**Comment by mltsy** [comment]
Has anybody tried adding link information to their serializers, as @chingor13 mentioned?  I have not, but it sounds like that might be a pretty good workaround until this is supported.  I'd love to know whether that works... if I get a chance, I'll try it out.

Obviously supporting shallow nesting without links would be great too.  However, I could also see just dropping all forms of automagic URL construction other than `/resources` and `/resources/1`... but that would prevent this from being useful for JSON:API-compatible services that don't return links, so scratch that ;)

Perhaps customizable procs that take parameters (which would vary depending on the action) and return a URL... for instance (if you had some odd routes):

```ruby
class Invoice < Base
  destroy_with ->(invoice) { [:delete, "/orders/#{invoice.order_id}/invoices/#{invoice.id}"] }
  create_with ->(invoice) { [:post, "/orders/#{invoice.order_id}/new_invoice"] }
  list_with ->(parent) { #  if API provides '/users/:id/invoices' and '/orders/:id/invoices'
    case parent
    when Order; "/orders/#{parent.id}/invoices"
    when User; "/users/#{parent.id}/invoices"
    end
  } 
  update_with ->(invoice) { :patch, "/orders/#{invoice.order_id}/invoices/#{resource.id}"]
end
```

**Comment by mltsy** [comment]
But then again, just supporting shallow nesting should probably be a simple flag on the model! ;)

```ruby
class Invoice < Base
  belongs_to :order, shallow: true
end
```

**Comment by gcrofils** [comment]
Any update on this ?
