### ISSUE TITLE
Can't use type as the name of an attribute

### ISSUE THREAD

**Issue by ChrisGF** [JsonApiClient/json_api_client#210]
Thank you very much for your work on this gem.  We are building connecting to an API that uses the json spec and your gem has been amazing.  

On thing that we have run into is that `type` is a pretty common attribute name.  Right now you are using it as a reserved word on the model.  But this breaks the json_api_spec as type is allowed in the attributes of a model.   

Do you have any plans to change this in the future?

**Comment by chingor13** [comment]
I hadn't really planned to do it, but it might be possible to rename the `type` to `_type`. We may want to have a fallback for `type` to try to not break anyone who might be using that accessor as it's technically in current the public api (whether it should have been or not is a different issue).

**Comment by pablocrivella** [comment]
According to the JSON API spec:
> A resource object’s attributes and its relationships are collectively called its “fields”.
   Fields for a resource object MUST share a common namespace with each other and with type and id. 
   In other words, a resource can not have an attribute and relationship with the same name, nor can it 
   have an attribute or relationship named type or id.

http://jsonapi.org/format/#document-resource-object-fields
