### ISSUE TITLE
Unable to set site outside of Base class

### ISSUE THREAD

**Issue by dmbrooking** [JsonApiClient/json_api_client#215]
So I have something similiar to the example code. If I do this:

```
module MyApi
  # this is an "abstract" base class that
  class Base < JsonApiClient::Resource
    # set the api base url in an abstract base class
    self.site = "http://example.com/"
  end
end
```

everything works.

If I try and set the site var outside of MyApi::Base, it fails.

If I have

```
MyApi::Base.site = "http://example.com/"
module MyApi
  # this is an "abstract" base class that
  class Base < JsonApiClient::Resource
  end
end
```

the connection fails with the error of 

```
     # Errno::ECONNREFUSED:
     #   Connection refused - connect(2) for nil port 80
```

Using pry, if I get the following:

```
[1] pry(#<RSpec::ExampleGroups::RecordType>)> MyApi::Base.site
=> "http://example.com/"
[2] pry(#<RSpec::ExampleGroups::RecordType>)> cd MyApi::Base
[3] pry(MyApi::Base):1> self.site
=> "http://example.com/"
[4] pry(MyApi::Base):1> site
=> "http://example.com/"
```

which is what I expect. I'm not sure what's happening...

**Comment by natemacinnes** [comment]
I have encountered this issue as well attempting to use the project in a multiple endpoint setup in different environments. 

I have different sites depending on whether or not I am in development, staging or production.

I discovered that all requests were going to the hard coded `site` and not the one that it was set to in the initializer from the the config file. 

I am looking into a fix now. 
Will keep you updated.

**Comment by natemacinnes** [comment]
The problem is that when the site class attribute is changed after boot the connection is never rebuilt. So the URL that Faraday uses for requests is never updated.

```
[1] >MyApi::Base.connection
=> #<JsonApiClient::Connection:0x007fa57b40fd30 @faraday=#<Faraday::Connection:0x007fa57b40fa60 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fa57b40f538 @handlers=[FaradayMiddleware::EncodeJson, JsonApiClient::Middleware::JsonRequest, JsonApiClient::Middleware::Status, EnjoyApi::Request, Faraday::Response::Logger, JsonApiClient::Middleware::ParseJson, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS https://myapi.com/>, @proxy=nil>>

In the JsonApiClient::Resource class you can see on line [104](https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/resource.rb#L104) the connection does not get rebuild per request. 
Calling `MyApi::Base.connection(rebuild: true)` will have the desired effect of changing updating the url in the connection to that of the resource's site. 
As seen in the _build_conneciton function on line [281](https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/resource.rb#L281)

**Comment by jessepollak** [comment]
I ran into this issue as well. It seems to me that this is a design-level issue with the library: primarily that it relies on a singleton connection to make all the requests. Ideally, there'd be a way to pass a connection object on a per-object/request basis, rather than maintaining that state at the class level.

**Comment by krainboltgreene** [comment]
Yeah, this totally kills my application's ability to communicate with multiple (yet similar) resources.

**Comment by wgrrrr** [comment]
I've opened #255 to discuss refactoring the storage of connection objects (which would impact this issue as well).

**Comment by gaorlov** [comment]
This looks resolved. Please reopen if not

**Comment by raldred** [comment]
@gaorlov This specific issue is not fixed.

```
Class Base < JsonApiClient::Resource
   self.site = 'http://host.com/v1'
end

Class Sub < Base
   self.site = 'http://host.com/v2'
end
```

The connection is still not rebuild and effectively caches the `site` in the `Base` class
The only solution currently is to use the workaround proposed by @natemacinnes 

This will rebuild the connection on setting `site` rebuild the connection and reapply the middleware
```
def self.site=(url)
    super(url)
    previous_middleware = connection.faraday.builder.handlers.map(&:klass)
    connection(true)
    current_middleware = connection.faraday.builder.handlers.map(&:klass)

    (previous_middleware - current_middleware).each do |middleware|
      connection.use(middleware)
    end
  end
```
