### ISSUE TITLE
get the related record fails for has_one relationships if the data is not included 

### ISSUE THREAD

**Issue by JohnSmall** [JsonApiClient/json_api_client#226]
It's possible for has_one type of relationships not to return the included record, only the id and the type. But the code expects the entire data to be in the 'included' section. If it's not there you get this error

    NoMethodError: undefined method `[]' for nil:NilClass
    etc/gems/json_api_client-1.3.0/lib/json_api_client/included_data.rb:43:in `record_for'

There are two tests for this, one expecting the included data, and one without the included data, but they both use stubbed JSON that has the included data. So the tests pass although the code doesn't actually work. When I changed the test so that the test for the case where there's no included data uses stubbed JSON that doesn't have included data, as it should do, then the test fails.

I'm trying to fix this, and might make a PR for it, but if it's a known problem and the fix is due out in the next release then I won't bother.

**Comment by adisos** [comment]
https://github.com/chingor13/json_api_client/issues/218

**Comment by JohnSmall** [comment]
@adisos Thanks for the vote and the link. I looked at the proposed fix [PR](https://github.com/blinkist/json_api_client/commit/#154c1870664ae22fad9896a44fcff04f708fb318) 

But that only prevents the error occurring when I'd expect the behaviour to be like ActiveRecord, which would go and fetch the required record. 

If I get time I'll look at it myself.

**Comment by JohnSmall** [comment]
See the PR. I've fixed the issue. Now if your response contains data for a has_one relationship, but does not include the full model in the included section, it will use the data id, and type, to get the model. So it behaves as you'd expect based on past experience with ActiveRecord.

**Comment by wgrrrr** [comment]
Also commented in #218, but is there anything I can do to push this along? It appears this is a good PR and will fix this bug.

This particular bug is causing me no end of pain. Would love to see it merged and released. 🥇

**Comment by gaorlov** [comment]
This looks resolved. Please reopen if not
