### ISSUE TITLE
`where` mutates original

### ISSUE THREAD

**Issue by AlexParamonov** [JsonApiClient/json_api_client#254]
`where` method should not do any mutation. New object have to be returned back.

so far hotfixed with:

```ruby
JsonApiClient::Query::Builder.prepend(
  Module.new do
    def where(conditions = {})
      dup.tap do |clone|
        clone.instance_variable_set(:@path_params, @path_params.merge(conditions.slice(*klass.prefix_params)))
        clone.instance_variable_set(:@filters, @filters.merge(conditions.except(*klass.prefix_params)))
      end
    end
  end
)
```

**Comment by gaorlov** [comment]
This is a problem for a few things. Do you have a PR for this? If not, I'll start one and would love some feedback on it. 

same core issue: https://github.com/JsonApiClient/json_api_client/issues/292

**Comment by AlexParamonov** [comment]
I've used hotfix mentioned above. Feel free to create a PR

**Comment by senid231** [comment]
#293 will solve it
