### ISSUE TITLE
Filter parameters set to `[]` are discarded

### ISSUE THREAD

**Issue by danbernier** [JsonApiClient/json_api_client#278]
## Observed behavior

When filtering, I'm seeing filter parameters get dropped if their value is an empty array.

```ruby
Resource.where(field: nil) #=> a GET to `/resources?filter[field]`, great!
Resource.where(field: [])  #=> a GET to `/resources`, with no filter params
```

## Expected behavior

I think empty array parameters should be passed through the same way as nil parameters are.

## Motivating example

I'm fetching a list of IDs to then fetch from the API (fetching them from a recommender, from user's favorites, etc), and it could be empty; when I look up the resources by ID, if the list is empty, then the API returns me the 25 latest resources.

```ruby
ids_to_query = calculate_list_of_ids
Resource.where(id: ids_to_query) # If it's empty, I get the 25 latest
```

We like the API's behavior, to return the latest 25 resources when there are no filter parameters, and we rely on it in other places, by specifying no filter criteria. But in this case, I want to filter by ID, and expect no results if there are no IDs.

## Other notes

From my testing:
* It's not about the field being named `id`; I also saw this when filtering by a fake field named `foo`
* It's not strictly about the empty array; I saw the same with an empty hash. For some reason, `nil`, empty strings, and whitespace strings are passed through; it's only empty arrays and hashes that are dropped. (Honestly, I can't see a reason for filtering by a hash, I was just testing different kinds of empty values.)

**Comment by senid231** [comment]
hi @danbernier 

same issue https://github.com/JsonApiClient/json_api_client/issues/283

as I say in it - it is an issue of `Faraday` and Im not sure how to handle it properly

```ruby
>> Faraday::NestedParamsEncoder.encode(filter: { field: ''})
=> "filter%5Bfield%5D="
>> Faraday::NestedParamsEncoder.encode(filter: { field: nil})
=> "filter%5Bfield%5D"
>> Faraday::NestedParamsEncoder.encode(filter: { field: []})
=> ""
>> Faraday::NestedParamsEncoder.encode(filter: { field: ['']})
=> "filter%5Bfield%5D%5B%5D="
>> Faraday::NestedParamsEncoder.encode(filter: { field: [nil]})
=> "filter%5Bfield%5D%5B%5D"
>> Faraday::NestedParamsEncoder.encode(filter: { field: ['foo']})
=> "filter%5Bfield%5D%5B%5D=foo"
```

I think we could convert `[]` to `nil` when building query but it should be optional behavior - it can break other people's code

**Comment by senid231** [comment]
I think better way will be to fix it on `Faraday` so i create appropriate issue and PR for it

**Comment by senid231** [comment]
@danbernier I've fixed this on `Faraday` side so you can just run `bundle update faraday` on your app to update `faraday` to `0.15.2` version
