### ISSUE TITLE
Where clause nested relationship and empty array. 

### ISSUE THREAD

**Issue by iseessel** [JsonApiClient/json_api_client#283]
`Order.where('subscription.id': []).to_a`returns all the orders on the json-api-resource, I expect it to return an empty array.

`Order.where(id: [])` also returns all the orders on the json-api-resource, I expect it to return an empty array.

Note: `Order.where('subscription.id': [1,2]).to_a` works as expected.

**Comment by iseessel** [comment]
Workaround: `Order.where(id: array.presence)`

**Comment by senid231** [comment]
Hi @iseessel 

this is an issue of `Faraday`

```ruby
>> Faraday::NestedParamsEncoder.encode(filter: { 'subscription.id': ''})
=> "filter%5Bsubscription.id%5D="
>> Faraday::NestedParamsEncoder.encode(filter: { 'subscription.id': nil})
=> "filter%5Bsubscription.id%5D"
>> Faraday::NestedParamsEncoder.encode(filter: { 'subscription.id': []})
=> ""
>> Faraday::NestedParamsEncoder.encode(filter: { 'subscription.id': ['foo']})
=> "filter%5Bsubscription.id%5D%5B%5D=foo"
```

I'm not sure what is a correct way to handle this.
Should `{ 'subscription.id': []}` be encoded to `"filter%5Bsubscription.id%5D%5B%5D="` or `"filter%5Bsubscription.id%5D%5B%5D"`?

**Comment by senid231** [comment]
I'm closing this one on favor of #278 
will free to continue conversation there
