### ISSUE TITLE
Allow passing relationships to new/create 

### ISSUE THREAD

**Issue by mjc** [JsonApiClient/json_api_client#290]
Currently this does not work:

```
[1] pry(#<PostTest>)> post = Post.new(name: "foo", core_post_id: 1, searchable: true, relationships: {user: User.find(1).first})
=> #<Post:@attributes={"type"=>"posts", "name"=>"foo", "body"="bar"}>
[2] pry(#<PostTest>)> post.save
NoMethodError: undefined method `as_json_api' for #<Hash:0x00007fc2e3a04968>
Did you mean?  as_json
from /Users/mjc/.gem/ruby/2.6.0/gems/json_api_client-1.5.3/lib/json_api_client/resource.rb:500:in `relationships_for_serialization'
```

I tried fiddling with things but this seems to be the expected syntax.   I also noticed that there are no tests for this functionality.

**Comment by clivecorbishley** [comment]
I found that the below worked for me, but couldn't find it documented anywhere - so I will create a PR for that soon.

```
post = Post.new(name: "foo")
post.relationships.user = User.find(1).first
post.save
```

**Comment by senid231** [comment]
Hi @mjc 

I've found that you can do it like this
```ruby
post = Post.new(name: "foo", core_post_id: 1, searchable: true, 'relationships' => {user: User.find(1).first})
```

because `JsonApiClient::Resource#initialize` only looks on `relationships` string key
I don't think that it's a correct behavior - we should use symbol keys or support indifferent access

**Comment by senid231** [comment]
Fixed.
Feel free to comment here if needed.
