### ISSUE TITLE
Pagination Customization Docs Confusing

### ISSUE THREAD

**Issue by jamesarosen** [JsonApiClient/json_api_client#291]
The [current pagination docs](https://github.com/JsonApiClient/json_api_client#custom-paginator) are a bit confusing. They suggest

```rb
JsonApiClient::Paginating::Paginator.page_param = "page[number]"
JsonApiClient::Paginating::Paginator.per_page_param = "page[size]"
```

But `JsonApiClient::Query::Builder#pagination_params` [wraps those](https://github.com/JsonApiClient/json_api_client/blob/b4e5804d957286df25c553d4baa16f155c846c3c/lib/json_api_client/query/builder.rb#L125-L127) in a `page: {…}`, resulting in URLs like
```
?page[page[number]]=2&page[page[size]]=20
```

Without overriding `#pagination_params`, there's no way to get rid of the `page[…]` wrapping. Moving the wrapping to `page_param` and `per_page_param` probably requires a major version bump. In the meantime, a little more documentation would help.

**Comment by senid231** [comment]
Readme fixed.
Feel free to comment here if needed.
