### ISSUE TITLE
Accessing included data that is only in the primary data

### ISSUE THREAD

**Issue by fusion2004** [JsonApiClient/json_api_client#299]
So, I'm having an issue that I'm not sure to which gem the fix should go. I'm requesting data from an index and including a relationship which references another record in that same data set, similar to this:

### `GET /tasks?include=parent`
```json
{
  "data": [
    {
      "id": "1",
      "type": "tasks",
      "attributes": {
        "text": "do thing"
      },
      "relationships": {
        "parent": {
          "data": null
        }
      }
    },
    {
      "id": "2",
      "type": "tasks",
      "attributes": {
        "text": "do other thing"
      },
      "relationships": {
        "parent": {
          "data": {
            "id": 1,
            "type": "tasks"
          }
        }
      }
    }
  ]
}
```

The gem I'm using is `jsonapi-resources`, and it seems to try and optimize this as shown: If the data you tried to include was in the primary dataset, then don't also add it to the included dataset. I can't seem to find any clear documentation in either the JSON API spec or recommendations regarding this case.

Would you be open to a PR implementing a lookup for included data that also checks the primary dataset? If so, should this gem default to using that fallback, or should it be a configuration setting?

**Comment by senid231** [comment]
@fusion2004 I think it should be configurable behavior (by default it should not lookup up in dataset)

**Comment by fusion2004** [comment]
Alrighty, hopefully we'll have time soon to package this into a PR!

**Comment by Fivell** [comment]
@senid231 maybe just a bug in jsonapi-resources, seems out of spec

**Comment by senid231** [comment]
@Fivell it's not a bug - it's a feature :)

really I think that it's nice, when you doesn't add same object twice - to data and included.
I've added optional support of this in #299

**Comment by fusion2004** [comment]
@senid231 Thanks for doing that, I never ended up getting the time to come back to this. Your implementation looks much simpler than what we hacked together, too.
