### ISSUE TITLE
Using filter on instance method doesn't work

### ISSUE THREAD

**Issue by mikemarsian** [JsonApiClient/json_api_client#301]
Currently it's impossible to use filter on instance method. The following doesn't work
```
user = MyAPI::User.new(id: 3)
user.administered_organizations.where(city: 'London')
```
Is there any workaround?

**Comment by senid231** [comment]
Hi @mikemarsian 
Can you provide more details about you problem?
Is `administered_organizations` a relationships?
What request should be sent?

If you have something like this
```ruby
module MyAPI
  class Base > JsonApiClient::Resource
    self.site = 'https://example.com/api'
  end
end

module MyAPI
  class User > Base
    has_many :administered_organizations
  end
end

module MyAPI
  class AdministratedOrganization > Base
    has_one :user
    property :city
  end
end
```

if you want to retrieve all organizations that belongs to user with `id=3` and has `city='London'`
you need to have `user_id` filter for `administered_organizations` resource

in this case you need to do this:
```ruby
MyAPI::AdministratedOrganization.where(user_id: 3, city: 'London')
```

**Comment by mikemarsian** [comment]
Actually I haven't defined any relationships between `Organization` and `User`. Should I? The documentation doesn't seem to say it's necessary.

This is what I did in the end:
```
user = WeAPI::User.new(id: admin_user.we_id)
response = user.administrated_organizations(:'filter[city]' => 'London')
```

**Comment by senid231** [comment]
@mikemarsian JSONAPI doesn't mention filters on relationship fetching
http://jsonapi.org/format/#fetching-relationships
So you can't fetch it like 
`https://example.com/my_api/users/123/administrated_organizations?filter[city]=London`

Because client doesn't know how to handle this request and it shouldn't know it.
Instead of this you need to do this
```ruby
MyAPI::AdministratedOrganization.where(user_id:  '123', city: 'London').to_a
```

You can add custom sugar method to `MyAPI::User` for this:
```ruby
def fetch_administrated_organizations(filters)
  MyAPI::AdministratedOrganization.where(user_id:  id, **filters).to_a
end
```

**Comment by senid231** [comment]
Closed due to inactivity.
Feel free to reopen this issue if needed.
