### ISSUE TITLE
When using pagination the token in the header is not being sent

### ISSUE THREAD

**Issue by crismethods** [JsonApiClient/json_api_client#302]
hey guys!

So we were trying to do this when sending our request for pagination:

```
def page(*args)
    with_headers(authorization: 'Bearer ' + token.token) do
        super(*args)
    end
end
```

but the request is not adding the token in the header:

```
I, [2018-09-27T16:25:01.375626 #49000]  INFO -- : get http:/users?page%5Bnumber%5D=1
D, [2018-09-27T16:25:01.375719 #49000] DEBUG -- request: User-Agent: "Faraday v0.12.2"
Content-Type: "application/vnd.api+json"
Accept: "application/vnd.api+json"
JsonApiClient::Errors::ConnectionError: JsonApiClient::Errors::ConnectionError
```

However when using `find` the header is correct:

```
I, [2018-09-27T16:24:25.743367 #49000]  INFO -- : get http:/users
D, [2018-09-27T16:24:25.743430 #49000] DEBUG -- request: User-Agent: "Faraday v0.12.2"
Authorization: "Bearer BLABLABLABLA"
Content-Type: "application/vnd.api+json"
Accept: "application/vnd.api+json"
```

And it is defined in the same way:

```
def find(*args)
    with_headers(authorization: 'Bearer ' + token.token) do
        super(*args)
    end
end
```

The only solution we found is to define the `connection` on this way:

```
      self.connection do |connection|
        # set OAuth2 headers
        connection.use FaradayMiddleware::OAuth2, token.token
      end
```

So now all the request contain the right header. 

We are wondering why this happens.

Thank you!

**Comment by crismethods** [comment]
Hi @senid231 , we are using `json_api_client 1.5.3`. And we have something like that:

```
  module AuthModule
    class Base < JsonApiClient::Resource
      class << self
        ...
        ...
        private
      
        def oauth_client
          @oauth_client ||= OAuth2::Client.new(app_id, app_secret, site: site)
        end

        def token
          if @token && !@token.expired?
            @token
          else
            @token = oauth_client.password.get_token(user, user_password)
          end
        end
      end
    
     self.connection do |connection|
       connection.use FaradayMiddleware::OAuth2, token.token
     end
  end
```

This is working as it inserts the token for every request to the API. Previously we overwrite each method (`find` for instance) wrapping it between `with_headers(...)`. However when we used `pagination`, the `with_headers` wrapping was not sending the `token` (we are not sure why). Then we started using `self.connection` in our `Base` class and now it works. However we have the situation that our `token` has an expiration, and using the `self.connection` way only requests the token the first time, and it doesnt call our `token` method again in the next calls, which eventually could lead to an `Invalid Token` from the `api` side. How could we manage this scenario? If `pagination` could insert the `token` correctly in the header when wrapping it into `with_headers` then we could just override each method and it could work as `token` is called on each request.

Thank you!

**Comment by senid231** [comment]
@crismethods I think you can do something like this:
```ruby
module WithExtendedHeaders
  extend ActiveSupport::Concern

  included do
    class_attribute :_extended_headers, instance_accessor: false
    self._extended_headers = []
  end

  class_methods do

    def extended_headers(&block)
      self._extended_headers << block
    end

    def inherited(subclass)
      subclass._extended_headers = []
    end

    def custom_headers
      result = super
        _extended_headers.each do |header_block|
        result = result.merge instance_exec(&header_block)
      end
      result
    end

  end
end

module AuthModule
  class Base < JsonApiClient::Resource
    include WithExtendedHeaders

    class << self do

      def oauth_client
        @oauth_client ||= OAuth2::Client.new(app_id, app_secret, site: site)
      end

      def token
        if @token && !@token.expired?
          @token
        else
          @token = oauth_client.password.get_token(user, user_password)
        end
      end

    end

    extended_headers do
      { authorization: "Bearer #{token.token}"
    end

  end
end
```

**Comment by crismethods** [comment]
Thank you so much @senid231 ! it works perfectly! we just needed to comment `subclass._extended_headers = []` as it was overwriting the headers we were passing, not 100% sure why. Amazing job, and excellent contribution from your side :)

**Comment by senid231** [comment]
@crismethods you're welcome

I've added
```ruby
def inherited(subclass)
  subclass._extended_headers = []
end
```
because we called `super` inside `custom_headers` which will gather headers from parent classes
in this case we don't need to copy extended_headers from parent class  - it will be there eventually

**Comment by crismethods** [comment]
@senid231 actually I applied the following change, and now it works in all the scenarios:

```
    module WithExtendedHeaders
      extend ActiveSupport::Concern

      included do
        class_attribute :_extended_headers, instance_accessor: false
        self._extended_headers = []
      end

      class_methods do
        def extended_headers(&block)
          _extended_headers << block
        end

        def inherited(subclass)
          subclass._extended_headers = _extended_headers
        end

        def custom_headers
          result = super
          _extended_headers.each do |header_block|
            result = result.merge instance_exec(&header_block)
          end
          result
        end
      end
    end
```

cheers!
