### ISSUE TITLE
Changelog for 1.6.1

### ISSUE THREAD

**Issue by gaorlov** [JsonApiClient/json_api_client#309]
@senid231 can you put together a list of changes for `1.6.1` and i can release it.

Thanks!

**Comment by senid231** [comment]
@gaorlov sure.
But I think we should include #300 to the next version too

**Comment by senid231** [comment]
## Fixes
* Use mocha/minitest instead of mocha/mini_test on test_helper #297
* Update arguments for custom connections run method in README #298
* import README - pagination override examples #306
* symbolize params keys on model initialize #307

## Features
* optional add default to changes #304

**Comment by senid231** [comment]
* define methods for properties and associations getter/setter #300

we will add this to features as well

**Comment by senid231** [comment]
@gaorlov I think you can release `1.6.1`

**Comment by gaorlov** [comment]
It is live. Thanks for all the hard work!

**Comment by senid231** [comment]
I've merge it into master and push tag

https://github.com/JsonApiClient/json_api_client/pull/310
https://github.com/JsonApiClient/json_api_client/releases/tag/v1.6.1
