### ISSUE TITLE
Breaking Change Between Versions 1.5.3 and 1.6.0

### ISSUE THREAD

**Issue by jamesstonehill** [JsonApiClient/json_api_client#313]
This is a breaking change.
`https://github.com/JsonApiClient/json_api_client/compare/v1.5.3...v1.6.0#diff-d3c016a418c89ad6c80f7c262736baa3L31`

`Connection#run` goes from having four arguments to three.

**Comment by senid231** [comment]
Indeed, it was breaking change.
It allows as to support functional that was described in spec.
Currently json_api_client doesn't use semantic versioning.
I've added information about breaking change into release.
