### ISSUE TITLE
Relations raise a error when added to a new record

### ISSUE THREAD

**Issue by code-bunny** [JsonApiClient/json_api_client#334]
When I have a record with a relation that needs to be set on create, I currently have to do a lot of hacky code in order to coerce the library to work with Rails forms. For instance

```
class User
  has_one :skill_level

  properties :first_name, type: :string
end

class SkillLevel
end
```

Expected result
```
user = User.new(first_name: 'Joe', relationships: { skill_level: SkillLevel.find(1).first })
user.relationships.skill_level # {"data"=>{"type"=>"skill-levels", "id"=>"1"}} 
user.skill_level # some instance of the skill_level
```

Actual result
```
user = User.new(first_name: 'Joe', relationships: { skill_level: SkillLevel.find(1).first })
user.relationships.skill_level # {"data"=>{"type"=>"skill-levels", "id"=>"1"}} 
user.skill_level # NoMethodError (undefined method `included' for nil:NilClass)
```

After some digging I have determined that the issue stems from the expectation that the last_result_set will have included data, even if this is a new model.

**Comment by senid231** [comment]
@code-bunny what version of `json_api_client` did you use?

**Comment by code-bunny** [comment]
@senid231 I am using 1.9.0, but have also tried master

**Comment by senid231** [comment]
@code-bunny looks like a missing feature

I've created draft PR for that

**Comment by code-bunny** [comment]
@senid231 thanks for getting to this, I look forward to trying out a fix as soon as you have one
