### ISSUE TITLE
Shall we release an update for this gem?

### ISSUE THREAD

**Issue by heidar** [JsonApiClient/json_api_client#340]
Hi friends.

The last release was in January and there was a PR released in March that actually fixed an issue I was having. How about doing another release to get it out?

Thanks!

**Comment by senid231** [comment]
@gaorlov can you release version?

**Comment by gaorlov** [comment]
Yessir. Later today

**Comment by gaorlov** [comment]
@senid231 I'm going to release `1.10.0`, but I have no idea what's in it. Can you please update the changelog?

**Comment by gaorlov** [comment]
@heidar @senid231 `1.10.0` is live.
