### ISSUE TITLE
warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

### ISSUE THREAD

**Issue by amondi-media** [JsonApiClient/json_api_client#367]
Ruby version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
Rails version: Rails 6.0.2.2

https://github.com/JsonApiClient/json_api_client/blob/db890adf3d7175e91829d359336ab7c98ed90a34/lib/json_api_client/schema.rb#L32

**Comment by dpep** [comment]
fixed by https://github.com/JsonApiClient/json_api_client/pull/370

**Comment by dpep** [comment]
FYI, it has not been merged yet...still waiting for approval
