### ISSUE TITLE
Support for Faraday > 2.x

### ISSUE THREAD

**Issue by bjedrocha** [JsonApiClient/json_api_client#407]
Hi, this library currently depends on an older version of `faraday` (1.x) and the now deprecated `faraday_middleware` gem. This makes it difficult to use this library alongside others that also build on top of `faraday` and use the 2.x versions. Any plans/wip to support newer versions of `faraday`? If not, would you consider a PR that adds support for it? It would likely be a breaking change for those that use the `connection` object directly. Thoughts?

**Comment by DavidHalman** [comment]
Just wanted to chime in that this would be fantastic. Currently we are getting a huge number of deprecation warnings, and we would like to get onto a more recent version of Faraday regardless.
