### ISSUE TITLE
When callbacks return false stop the execution of the method

### ISSUE THREAD

**Issue by klaut** [JsonApiClient/json_api_client#98]
I love the addition of the callbacks!

I have one question: is it possible to stop the execution of the method when a callback returns false? Similar to ActiveRecord.

Say, I have a `before_create` callback but I want to check if some conditions are true and only then proceed to executing the `create` method. Would that be possible?

Thank you,
Tanja

**Comment by Fivell** [comment]
@klaut , according to docs like the Active Record methods, the callback chain is aborted as soon as one of the methods in the chain returns false. http://api.rubyonrails.org/classes/ActiveModel/Callbacks.html

**Comment by senid231** [comment]
in release [v1.0.0.beta6](https://github.com/chingor13/json_api_client/releases/tag/v1.0.0.beta6) json_api_client include `ActiveModel::Callbacks` so it has same behavior as callbacks in `ActiveRecord`

**Comment by senid231** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
